<?php

namespace AppBundle\Repository;

/**
 * TirageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TirageRepository extends \Doctrine\ORM\EntityRepository
{
}
